# Generated by Django 4.2.1 on 2023-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistration',
            name='department',
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='profile',
            field=models.FileField(upload_to='static\\patients'),
        ),
    ]
