# Generated by Django 4.2.1 on 2023-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_remove_patientregistration_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patienthistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itching', models.CharField(max_length=5, null=True)),
                ('skin_rash', models.CharField(max_length=5, null=True)),
                ('nodal_skin_eruptions', models.CharField(max_length=5, null=True)),
                ('continuous_sneezing', models.CharField(max_length=5, null=True)),
                ('shivering', models.CharField(max_length=5, null=True)),
                ('chills', models.CharField(max_length=5, null=True)),
                ('joint_pain', models.CharField(max_length=5, null=True)),
                ('stomach_pain', models.CharField(max_length=5, null=True)),
                ('acidity', models.CharField(max_length=5, null=True)),
                ('ulcers_on_tongue', models.CharField(max_length=5, null=True)),
                ('muscle_wasting', models.CharField(max_length=5, null=True)),
                ('vomiting', models.CharField(max_length=5, null=True)),
                ('burning_micturition', models.CharField(max_length=5, null=True)),
                ('spotting_urination', models.CharField(max_length=5, null=True)),
                ('fatigue', models.CharField(max_length=5, null=True)),
                ('weight_gain', models.CharField(max_length=5, null=True)),
                ('anxiety', models.CharField(max_length=5, null=True)),
                ('cold_hands_and_feets', models.CharField(max_length=5, null=True)),
                ('useremail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
