# Generated by Django 4.2.1 on 2023-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_patienthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='disease',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
