# Generated by Django 4.2.1 on 2023-09-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_patienthistory_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentdate', models.DateField(auto_created=True, null=True)),
                ('reqid', models.CharField(max_length=5, null=True)),
                ('patientemail', models.EmailField(max_length=254, null=True)),
                ('doctoremail', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
    ]
