# Generated by Django 4.2.1 on 2023-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='appointmentdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
