# Generated by Django 4.2.1 on 2023-09-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_alter_requests_appointmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='pid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
