# Generated by Django 4.2.1 on 2023-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_patienthistory_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='slno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
