# Generated by Django 4.2.1 on 2024-01-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Patient", "0008_requests_slno"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_group", models.CharField(max_length=10)),
                ("units", models.IntegerField()),
                ("hospital_name", models.CharField(max_length=100)),
                ("hospital_address", models.TextField()),
            ],
        ),
    ]
