# Generated by Django 4.2.1 on 2024-01-09 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Patient", "0009_blooddonation"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blooddonation",
            table="BloodDonation",
        ),
    ]
