# Generated by Django 4.2.1 on 2024-01-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Patient", "0010_alter_blooddonation_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blooddonation",
            name="blood_group",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="blooddonation",
            name="hospital_address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="blooddonation",
            name="hospital_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blooddonation",
            name="units",
            field=models.IntegerField(null=True),
        ),
    ]
