# Generated by Django 4.2.1 on 2023-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docregistration',
            name='profilename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
