# Generated by Django 4.2.1 on 2023-09-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_docregistration_profilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20, null=True)),
                ('myfile', models.FileField(upload_to='static\\reports')),
                ('patientemail', models.EmailField(max_length=254, null=True)),
                ('doctoeremail', models.EmailField(max_length=254, null=True)),
                ('filecontent', models.TextField(null=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
