# Generated by Django 4.2.1 on 2023-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_rename_doctoeremail_reportupload_doctoremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportupload',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
