# Generated by Django 4.2.1 on 2023-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_reportupload_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportupload',
            name='reqid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
