# Generated by Django 4.2.1 on 2024-01-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0006_reportupload_reqid"),
    ]

    operations = [
        migrations.AddField(
            model_name="docregistration",
            name="hospitaladdress",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="docregistration",
            name="hospitalname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
