# Generated by Django 4.2.1 on 2024-01-09 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0007_docregistration_hospitaladdress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docregistration",
            name="address",
        ),
    ]
