# Generated by Django 4.2.1 on 2024-01-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Doctor", "0008_remove_docregistration_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="docregistration",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
